version: "3.9"
services:
  db:
    image: postgres:12.5-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web: &web
    build: .
    command: bash -c "rm -rf /code/tmp/pids && foreman start -f Procfile.dev"
    volumes:
      - .:/code
    ports:
      - 3000:3000
    depends_on:
      - db
    environment: &envs
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: password
  next:
    <<: *web
    command: bash -c "rm -rf /code/tmp/pids && bundle exec rails s -b 0.0.0.0"
    environment:
      <<: *envs
      BUNDLE_GEMFILE: Gemfile.next
volumes:
  db_data:
