// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from './application'

import ResizeFieldController from './resize_field_controller'
application.register('resize-field', ResizeFieldController)

import FocusFieldController from './focus_field_controller'
application.register('focus-field', FocusFieldController)

import SidebarController from './sidebar_controller'
application.register('sidebar', SidebarController)

import ImcController from './imc_controller'
application.register('imc', ImcController)
