// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from './application'

import ImcController from './imc_controller'
application.register('imc', ImcController)

import ResizeFieldController from './resize_field_controller'
application.register('resize-field', ResizeFieldController)

import SearchController from './search_controller'
application.register('search', SearchController)

import SidebarController from './sidebar_controller'
application.register('sidebar', SidebarController)

import PatientsInformationController from './patients/information_controller'
application.register('patients--information', PatientsInformationController)

import HwComboboxController from "@josefarias/hotwire_combobox"
application.register("hw-combobox", HwComboboxController)
