name: current rails application
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:10.13
        ports: ["5432:5432"]
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Run linter
        run: bundle exec standardrb
      - name: Run test suite
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:password@localhost:5432/doctors_test
          TZ: America/Mexico_City
        run: |
          bin/rails db:create
          bin/rails db:schema:load
          bin/rake
      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocation: ${{github.workspace}}/coverage/.resultset.json:simplecov
          debug: true
