name: current rails application
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:10.13
        ports: ["5432:5432"]
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Run rubocop
        run: bundle exec rubocop
      - name: Setup Code Climate test-reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          GIT_BRANCH=$GITHUB_HEAD_REF GIT_COMMIT_SHA=$GITHUB_SHA ./cc-test-reporter before-build
      - name: Run test suite
        env:
          COVERAGE: true
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:password@localhost:5432/doctors_test
          TZ: America/Mexico_City
        run: |
          bin/rails db:create
          bin/rails db:schema:load
          bundle exec rspec --format progress --profile
      - name: Puts git stuff
        run: |
          echo $GIT_BRANCH;
          echo $(git rev-parse origin/$GITHUB_HEAD_REF);
      - name: Publish code coverage
        run: GIT_BRANCH=$GITHUB_HEAD_REF GIT_COMMIT_SHA=$GIT_COMMIT_SHA ./cc-test-reporter after-build -t simplecov --exit-code $?
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
