name: build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13-alpine
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: postgres

    steps:
      - uses: actions/checkout@v2

      - name: Set timezone to America/Mexico_City
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "America/Mexico_City"

      - name: Set up Ruby 2.7
        uses: ruby/setup-ruby@v1

      - name: Cache Ruby gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: Bundle gems
        run: |
          bundle config path vendor/bundle
          bundle config set without "production development"
          bundle config --local build.sassc --disable-march-tune-native
          bundle install --jobs 4 --retry 3

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Node modules
        run: yarn install --frozen-lockfile

      - name: Add hosts to /etc/hosts
        run: |
          sudo echo "0.0.0.0 ursula.lvh.me" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 ursula.lvh.me" | sudo tee -a /etc/hosts

      - name: Run Tests
        env:
          DB_HOST: localhost
          DB_USER: postgres
          DB_PASSWORD: postgres
          RAILS_ENV: test
          SECRET_KEY_BASE: we-dont-need-a-secret-here
          # DOMINIO: http://localhost
          # PORT: 3000
        run: |
          bundle exec rake db:create db:schema:load
          bundle exec rake spec
